### ISSUE TITLE
Use django-bootstrap-v5

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#12]
this is fine, but easier is https://django-bootstrap-v5.readthedocs.io/en/latest/ - then you don't have to list these urls manually

_Originally posted by @bbelderbos in https://github.com/JAWD-001/peer_mentoring/pull/11#discussion_r1144880405_

**Comment by JAWD-001** [comment]
Have this installed. Does the forms work with ModelForms or will I have to do all with forms from now on? Reading through the docs now

**Comment by JAWD-001** [comment]
Also, what's up with npm for icons? I need to install the npm for icons in the project or no?

**Comment by JAWD-001** [comment]
This is more for when we get to templates though right? Are we building the backend completely first? Can we please?

**Comment by bbelderbos** [comment]
@JAWD-001 it would be nice to get this issue done this week, current view:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/387927/228269888-1ce6f443-d327-4cee-823c-2a4ad692442b.png">

**Comment by bbelderbos** [comment]
Yes please.

**Comment by JAWD-001** [comment]
Okay, I have the nav up. Can we chat a little about what the different bootstrap assets are so that I can start thinking through design? Also, can I get some tips/help on designing a nice looking website?

**Comment by bbelderbos** [comment]
What do you mean bootstrap assets? 

I would just go with a simple standard bootstrap design for now, keeping things simple because there is still quite some back-end work to do. 

For later on: people have used this in PDM: https://github.com/ColorlibHQ/gentelella - I cc'd you on a Slack thread FYI.
