### ISSUE TITLE
Add navigation to site

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#15]
Part of https://github.com/JAWD-001/peer_mentoring/issues/12 - just grab navbar element from bootstrap docs and add links to the different website pages / features. Now when you login it's not yet clear where to go.

**Comment by JAWD-001** [comment]
Done with this, I put it in the base.html. I was thinking for the groups drop-down we can list by category. Also, search would be great, but should it be reserved to groups index and maybe groups detail to search for post topic? What's your take?

**Comment by bbelderbos** [comment]
Search is interesting, it's two fold right? Public content vs private group content, so need to do some filtering / permission checks. Deferring into issue now.

**Comment by JAWD-001** [comment]
Also, thinking that a landing page without the navbar for signup would be best. Something similar to how github is different when not authenticated vs. once you sign in

**Comment by bbelderbos** [comment]
Good point, you can do an if / else in the template, we could also hide it when logged out perhaps? You can check that with `request.user.is_authenticated` in the template.

**Comment by bbelderbos** [comment]
nice
