### ISSUE TITLE
Make a view to join groups

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#16]
When I go to http://localhost:8000/groups/ I expect to see groups and have the ability to join them. Is that how it should work?

**Comment by bbelderbos** [comment]
Also is group creation done in the front-end or shall we leave that as something to be done in the admin?

**Comment by JAWD-001** [comment]
front-end, so you think that we should have it in the list view?

**Comment by bbelderbos** [comment]
So we have group creation and group joins.

Group creation: who can create groups, any logged in user, or does it require a certain role or permission?

Group joins: once the group is created, can anybody join? Maybe good to talk it through tomorrow, you could also make a mock up how you want this to look for the end user, that will help with implementation.

**Comment by JAWD-001** [comment]
Group creation: I was thinking anyone, but do you think that should be limited? Just because I can't predict anyone's needs and I don't want to have to sift through those requests and instantiate them. 

Group join: I would say yes, but the ability of the admin of the group to ban people

**Comment by bbelderbos** [comment]
Good point, it would be good for a user to be able to start a group, similarly how anybody (with right permissions) can open a slack channel or multi-user DM.  Ok regarding the join, I will defer banning people in an issue now.

**Comment by JAWD-001** [comment]
The ability to join a group has been added. It's a second view that renders the group detail. Can/should we just add it to the group detail function? If not, can/how do we store it in a button like modal?

**Comment by bbelderbos** [comment]
Did we address this today? https://github.com/JAWD-001/peer_mentoring/pull/27/files

**Comment by JAWD-001** [comment]
Yes, I think so

**Comment by JAWD-001** [comment]
Have this on the group index, and it changes if you are in the group or not.

**Comment by bbelderbos** [comment]
Can continue here: https://github.com/JAWD-001/peer_mentoring/issues/38
