### ISSUE TITLE
Implement a simple content search

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#20]
Done with this, I put it in the base.html. I was thinking for the groups drop-down we can list by category. Also, search would be great, but should it be reserved to groups index and maybe groups detail to search for post topic? What's your take?

_Originally posted by @JAWD-001 in https://github.com/JAWD-001/peer_mentoring/issues/15#issuecomment-1489028554_

**Comment by JAWD-001** [comment]
Was looking through documentation on this. Should we switch to Postgres yet? The documentation lists Postgres specific documentation for it.

**Comment by bbelderbos** [comment]
Does not seem related to the issue? But yes, I would mirror prod <> dev so it would be good to use a postgres db locally if you are going to use that in production as well. Let me know if you get postgres installed successfully, then you can set a db url in .env like this:

```
DATABASE_URL=postgres://user:pw@0.0.0.0:5432/your_db
```

**Comment by JAWD-001** [comment]
Should we use a simple content search or should we switch to postgres and use the postgres text search stuff? Apparently it's better optimized

**Comment by JAWD-001** [comment]
Should we keep this search method with Postgres or use the postgres optimized full-text search when we swtich over?

**Comment by bbelderbos** [comment]
I think you already implemented this, just straight ORM for now, and yep feel free to switch to postgres when ready to emulate production db better locally.
