### ISSUE TITLE
Ability for an admin to ban people from a group

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#21]
Group creation: I was thinking anyone, but do you think that should be limited? Just because I can't predict anyone's needs and I don't want to have to sift through those requests and instantiate them. 

Group join: I would say yes, but the ability of the admin of the group to ban people

_Originally posted by @JAWD-001 in https://github.com/JAWD-001/peer_mentoring/issues/16#issuecomment-1489035672_

**Comment by JAWD-001** [comment]
Hey bob, was working with the idea of making the creator of a group automatically added as an admin. Ran into an circular import issue when editing the group model when I tried to import the UserProfile model. Is there a way around this or should we drop the groups_joined off of the userprofile model and just have the groups have a foreign key to the UserProfile model for admin and then create a foreign key field of members from the UserProfile model?

**Comment by JAWD-001** [comment]
Nvm, I figured it out. I added the groups_moderated to the user profile object. I didn't push migrations yet because I wanted your feedback on it to make sure that's the best design.

**Comment by bbelderbos** [comment]
Cool, so all good here? Commit of fix?

**Comment by JAWD-001** [comment]
No, cause I was thinking through it the other day. Should we just have a members and mod fields on the group model? Instead of having it on the user profile model? If not then I guess that I could just make an it statement that populated a button to be able to remove a member from the view members template that I'll make.

Is this making sense?

**Comment by bbelderbos** [comment]
Let's look at this on our call today.

**Comment by bbelderbos** [comment]
Leaving groups joined on profile page. Fixed circular import by using User model: https://github.com/JAWD-001/peer_mentoring/pull/32/files - leaving issue open for the banning part.
