### ISSUE TITLE
Group Posts 

### ISSUE THREAD

**Issue by JAWD-001** [JAWD-001/peer_mentoring#25]
Group posts are still not showing up, I changed the dictionary to be posts and implemented a for loop for post in posts on group_detail, still doesn't populate the context data.

**Comment by bbelderbos** [comment]
@JAWD-001 did your fix this?

**Comment by JAWD-001** [comment]
Hey bob, not yet.

**Comment by JAWD-001** [comment]
Hey bob, I just updated code. Still can't get this. I've tried even posting all posts and still can't get it

**Comment by JAWD-001** [comment]
Got it! Still need help with the user profile page

**Comment by bbelderbos** [comment]
cool, I did not see a PR? where is the code?

**Comment by JAWD-001** [comment]
PR done, wanted to wait until I tried some more on the other two issues that I am having.

**Comment by bbelderbos** [comment]
Fixed :)
