### ISSUE TITLE
Chat stopped working, debug ...

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#28]
Hey Bob, this is done. Just updated the button link to bootstrap 5. However, the websocket disconnects still. Can you look into it and I will as well tonight?

_Originally posted by @JAWD-001 in https://github.com/JAWD-001/peer_mentoring/issues/18#issuecomment-1496450673_

**Comment by JAWD-001** [comment]
I have it working again, but have to start up the redis docker container, so would need to figure out how to do that for the deployed app

**Comment by bbelderbos** [comment]
Sorry did not look into it, so the issue was caused by redis not running? That makes sense.

**Comment by JAWD-001** [comment]
Need to figure out how to run it in docker when deployed

**Comment by bbelderbos** [comment]
Melé's chapter is pretty good and covers chat.

**Comment by bbelderbos** [comment]
Yeah this was redis not running, closing.
