### ISSUE TITLE
Use Postgres locally

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#31]
Was looking through documentation on this. Should we switch to Postgres yet? The documentation lists Postgres specific documentation for it.

_Originally posted by @JAWD-001 in https://github.com/JAWD-001/peer_mentoring/issues/20#issuecomment-1523479910_

**Comment by JAWD-001** [comment]
Should we use a postgres docker container or no? Was reading somewhere that it's better to use the containerized db (safer).

**Comment by bbelderbos** [comment]
You can but I don't use that for local development.

**Comment by bbelderbos** [comment]
I think you did this one right? Did you go with native postgres (no docker)?

**Comment by JAWD-001** [comment]
No, I didn't. Wanted your advice on using docker to deploy or not.

**Comment by bbelderbos** [comment]
So do you have postgres running then? 
I would not use Docker to run Postgres locallly.
For deployment, let's see what AWS - which you prefer to use - typically recommends / offers.

**Comment by bbelderbos** [comment]
recommend command line tool for postgres (nicer shell): https://www.pgcli.com/install
