### ISSUE TITLE
Render images on group pages

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#33]
They show now in the template, but not rendering yet: https://github.com/JAWD-001/peer_mentoring/pull/32/files - can you investigate further @JAWD-001 ?

_Originally posted by @bbelderbos in https://github.com/JAWD-001/peer_mentoring/issues/22#issuecomment-1523767077_

**Comment by bbelderbos** [comment]
@JAWD-001 didn't you fix this already?

**Comment by JAWD-001** [comment]
No, can you help me with this today?

**Comment by bbelderbos** [comment]
Of course!

**Comment by JAWD-001** [comment]
Will this also change once we add the S3 bucket?

**Comment by bbelderbos** [comment]
Yes we could make it so that you upload the image to S3 and save the link in the db, you can use this script: https://github.com/PyBites-Open-Source/pybites-tools/blob/main/pybites_tools/aws.py

**Comment by bbelderbos** [comment]
Logged new issue: https://github.com/JAWD-001/peer_mentoring/issues/81
