### ISSUE TITLE
Extra step in join flow

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#39]
First sent to moderator for approval, I started a request table here: https://github.com/JAWD-001/peer_mentoring/pull/37/files

So a request comes in there first, then make a new view for the moderator to approve these requests. Upon approving you update the group.members ... 

Maybe make a note here how you would do this step by step and I will comment further ...

**Comment by JAWD-001** [comment]
join comes in 

moderators have join requests approve will be an update to members list of groups and delete the request from the model, deny will delete the request off of the model.

**Comment by bbelderbos** [comment]
@JAWD-001 kudos / great job on the whole approval flow you introduced this week 😍
