### ISSUE TITLE
bug: group join crashes

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#56]
reproduction steps: 
- user1 created group
- user2 uses the join button to join the newly created group

crash:

<img width="1641" alt="Screenshot 2023-06-06 at 16 47 48" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/5e5e143b-d332-421c-b706-b3333a148f18">

**Comment by JAWD-001** [comment]
Could not replicate, so, done?

**Comment by bbelderbos** [comment]
I will try once more, but for now close then.
