### ISSUE TITLE
remove hard coded post comment count

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#60]
I can show you how we have done this on the platform:

<img width="1132" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/10c9f2d9-42d9-4f06-b724-0156502074fc">

But I also feel this is less of a priority now given the other issues we need to fix / finish for MVP.

**Comment by JAWD-001** [comment]
Something like? q = Post.objects.annotate(Count("comments")).

**Comment by JAWD-001** [comment]
group_post_count = Group.objects.annotate(Count("posts")

**Comment by JAWD-001** [comment]
Then return them as context variables and then call them on the template?

**Comment by JAWD-001** [comment]
I pushed code for this, it's not working as intended, but I have a dynamic count now.

**Comment by bbelderbos** [comment]
OK will review, what branch?

Yep use annotate, see https://chat.openai.com/share/8731673c-4b66-4645-a1d8-17af2a3a5a19

**Comment by JAWD-001** [comment]
Main updates. I got it! But it doesn’t dynamically work for each post.Thank you,James Dycus, M.Ed.Sent from my iPhoneOn Jun 12, 2023, at 5:56 AM, Bob Belderbos ***@***.***> wrote:﻿
OK will review, what branch?
Yep use annotate, see https://chat.openai.com/share/8731673c-4b66-4645-a1d8-17af2a3a5a19

**Comment by bbelderbos** [comment]
So annotate code so far is on main branch? Let me play with it then ...

**Comment by JAWD-001** [comment]
Yes, and it works so done.

**Comment by bbelderbos** [comment]
awesome
