### ISSUE TITLE
“friend request” button on user profile

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#62]
request approval page done

... and with this issue I think I captured all from required actions from our yesterday's chat.

**Comment by JAWD-001** [comment]
done with a generic button, but workflow is completed as well

**Comment by bbelderbos** [comment]
cool, where did you commit it? I don't see a new PR?

**Comment by JAWD-001** [comment]
Done for the button on the user profile index too.

**Comment by bbelderbos** [comment]
Nice, is it all in main?

**Comment by bbelderbos** [comment]
I hit another issue here, weird because I thought this worked well before? Can you check please? https://github.com/JAWD-001/peer_mentoring/issues/69
