### ISSUE TITLE
friend reject fails

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#67]
added friend, friend then rejects, then I get this:

<img width="1641" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/ab44280d-2409-4aee-bd0d-9f5f08c136cc">

can you check please?

**Comment by JAWD-001** [comment]
Error on the view redirect namespace. Had account_manage, but needed account_management

**Comment by bbelderbos** [comment]
ok great!
