### ISSUE TITLE
find mentor page shows self

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#68]
Created a new db to start fresh, with only me as user in the db, I show up under user_index, is that intended? 

<img width="398" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/fdaea756-cd9d-46e9-852d-4ba7aa7ca892">

**Comment by JAWD-001** [comment]
Doesn't really bother me since you can't add yourself.

**Comment by JAWD-001** [comment]
Actually, might be nice to exclude. I tried, but wasn't getting it. I tried throwing an {% if profile != request.user %} before the profile card, but still keep request.user from rendering. Should we .remove(request.user) from the users variable in the view?

**Comment by JAWD-001** [comment]
.exclude()
