### ISSUE TITLE
add friend bug

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#69]
hm something seems off now, here I am tim:

<img width="381" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/2dc31503-b121-4175-9bae-0a8f9dfeb33b">

when adding bob, the request does not show up under bob's account but under the requester's account (tim):

<img width="609" alt="image" src="https://github.com/JAWD-001/peer_mentoring/assets/387927/b63b598f-634a-4385-b497-325f6249819e">

can you check please?

**Comment by JAWD-001** [comment]
This is interesting too because it only happens on the friend request button on the index, the one on the user profile page works correctly

**Comment by JAWD-001** [comment]
Fixed!

**Comment by bbelderbos** [comment]
Nice, do you have the commit hash of the fix?
