### ISSUE TITLE
use sendgrid (or another cloud provider) for emailing

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#7]
Not for now, but when time comes, mentioned in this comment: https://github.com/JAWD-001/peer_mentoring/commit/1567636f3f24c14b6087e11ec32659800fd9f13c#r103245811

**Comment by JAWD-001** [comment]
I have a sendgrid account, I'll link it up and let me know what you think.

**Comment by JAWD-001** [comment]
Have sendgrid setup, based on docs. Will test soon.

**Comment by JAWD-001** [comment]
Still not sending emails, but I'll look into soon.

**Comment by JAWD-001** [comment]
Got themanupapp.comThank you,James Dycus, M.Ed.Sent from my iPhoneOn May 9, 2023, at 1:18 PM, Bob Belderbos ***@***.***> wrote:﻿
(app).io maybe?

**Comment by bbelderbos** [comment]
@JAWD-001 did you get email working? We can confirm next week with deployment

**Comment by JAWD-001** [comment]
Almost, I just have to verify my domain with them. I’m getting an error cause I don’t have a verified domain yet.Thank you,James Dycus, M.Ed.Sent from my iPhoneOn Jun 7, 2023, at 3:30 AM, Bob Belderbos ***@***.***> wrote:﻿
@JAWD-001 did you get email working? We can confirm next week with deployment

**Comment by bbelderbos** [comment]
Yes that's a required step, but easy to do in their GUI and confirming the email they will send.
