### ISSUE TITLE
set up pre-commit

### ISSUE THREAD

**Issue by bbelderbos** [JAWD-001/peer_mentoring#8]
I recommend setting up https://pre-commit.com to at least run black + flake8 upon git commit (you can also add isort, pyupgrade and mypy)

My YouTube guide: Increase Python code quality with pre-commit - https://www.youtube.com/watch?v=XFyLzr5Ehf0
+ related code clinic: https://pybites.mykajabi.com/products/pybites-coaching-calls-2/categories/3469727/posts/2152387423

**Comment by JAWD-001** [comment]
I set this up, however, getting an issue with flake 8. It prompts me to login to gitlab; this mean that I need a gitlab account? Should I have had one all along?

**Comment by JAWD-001** [comment]
It's been fixed and it worked on last push
